name: dicoding_app_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  syncfusion_flutter_charts: ^26.2.14
  animated_text_kit: ^4.2.2
  flutter_riverpod: ^2.5.1
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/