name: submission1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  
  flutter_cache_manager: ^3.4.1
  flutter_web_plugins:
    sdk: flutter

  google_fonts: ^6.2.1
  http: ^1.3.0
  image_picker: ^1.1.2
  image_picker_windows: ^0.2.1+1
  intl: ^0.19.0
  provider: ^6.1.4
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  app_settings: ^6.1.1
  json_annotation: ^4.7.0
  freezed_annotation: ^2.2.0
  freezed: ^2.2.1
  google_maps_flutter: ^2.12.1
  google_maps_flutter_web: ^0.5.12
  geocoding: ^3.0.0
  location: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.3.2
  json_serializable: ^6.5.4

flutter:
  generate: true
  uses-material-design: true
